### ISSUE TITLE
CI stage 'Install MS SQL Server' takes up to 30 minutes

### ISSUE THREAD

**Issue by tznind** [SMI/IsIdentifiable#121]
![image](https://user-images.githubusercontent.com/31306100/180423745-bdf6a0f0-7c3c-484a-b40f-6b29f355d35e.png)

**Comment by tznind** [comment]
And now we are back down to '5m 46s'.  Maybe some kind of bandwidth thing or just ms sql server image being slow for some reason.  Going to close this for now unless you have any immediate suggestions @jas88

**Comment by jas88** [comment]
@tznind Occasionally the servers glitch somewhere, and it gets stuck retrying the download - usually it either works OK, or times out and fails totally, looks like this one fell in the middle somewhere and completed eventually (could be the servers came back online after 20 mins?)

**Comment by jas88** [comment]
@rkm the Windows one is something like a 1.7GB ISO, caching it wouldn't be a benefit 99% of the time - "MSSQL fails to install occasionally, just hit 'retry' if it does" isn't quite as technically elegant but avoids overhead the rest of the time.

Chocolatey does have a caching CDN available for paying customers, which would do this for us on Windows builds - no idea what pricing is like or if they have a discount we might benefit from, if we do need caching?
