### ISSUE TITLE
Package uk.ac.dundee.hic.nerd as self contained executable

### ISSUE THREAD

**Issue by tznind** [SMI/IsIdentifiable#16]
Rationale is in https://github.com/SMI/IsIdentifiable/issues/15 .  This ticket is for the java side of things.

> Hey how feasible is it to make nerd work without having to install java? is there a packer that will build it as a .exe rather than a jar and bundle only the dependencies of java needed to run it?

> Yep, it's possible, I'll give it a try in a few days I think

Ideally I would like to see the following working without installing either java or python on end users computers:
`ii start spaCy 1882`
`ii start stanford 1881`

**Comment by jas88** [comment]
NER's model-loading code isn't compatible with the current native-image Java compiler, so the best we can do is an executable JAR file - there will need to be a JRE installed for the foreseeable future. Just running/double-clicking the JAR file will work though.

**Comment by jas88** [comment]
Finally got it working using a different approach! Implemented in #170
