### ISSUE TITLE
CHI regex matches invalid identifiers

### ISSUE THREAD

**Issue by rkm** [SMI/IsIdentifiable#216]
https://github.com/SMI/IsIdentifiable/blob/b8f7edb8e6e12895f7e337d7253a305d7911c3db/IsIdentifiable/Runners/IsIdentifiableAbstractRunner.cs#L43

Will match `0000000000`, `0000000001`, and other values where the first six digits aren't valid combinations of `DDMMYY`.

**Comment by jas88** [comment]
Fixed in #247
